---
title: "Notas"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, cache=FALSE}
source("setup_knitr.R")
library(ggplot2)
library(tidyverse)
library(viridis)
```

## Escolha a aba de sua turma {.tabset}

### CE001-MB

```{r notasmb}
mb <- read.csv2('misc/notas-MB.csv')
mb <- mb[order(mb$Matrícula), ]
kable(mb, row.names = FALSE)
```


```{r plotmb, out.width = '100%'}
data1 <- rbind(mb[which(rowSums(!is.na(mb[,2:ncol(mb)]))>0),], 
               data.frame(Matrícula='', mb[1,-1]*0))
ns <- ncol(data1)-1
na <- nrow(data1)
data1$Total <- rowSums(data1[,2:(ns+1)], na.rm=TRUE)
data1$Aluno <- substring(data1$Mat, 8)
data1 <- data1[order(data1$Aluno),]
angle <- 90 -360*(1:na-0.5)/na
data1$angle <- ifelse(angle<(-90), angle + 180, angle)
data <- data.frame(
  Aluno=rep(data1$Aluno, ns), 
  Etapa=rep(paste0('E', 1:ns), each=na), 
  Nota=unlist(data1[,2:(ns+1)]))
p = ggplot(data) +      
  # Add the stacked bar
  geom_bar(aes(x=as.factor(Aluno), y=Nota, fill=Etapa), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete=TRUE) +
  ##geom_abline(slope=0, intercept=0:ns*70, col=c('gray'))+
  geom_abline(slope=0, intercept=c(ns*c(40,70), 7*70), col=c('red', 'green', 'blue'))+
##  annotate("text", x = rep(1.5, ns+1), y = 70*0:ns, label = sprintf('%02d', 70*0:ns) , color="brown", size=3, hjust=1, angle=45) +
  annotate("text", x = 1, y = c(ns*c(40,70), 7*70), label = sprintf('%02d', c(ns*c(40,70), 7*70)), color=c('red','green','blue'), size=4 , angle=45, hjust=0.5) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0,4), "cm") 
  ) +
  geom_text(data=data1, aes(x=Aluno, y=max(data1$Total)+50, label=Aluno), color="black", fontface="bold",alpha=0.6, size=3, angle=data1$angle, inherit.aes = FALSE ) +
  coord_polar()  
  ##geom_text(data=data1, aes(x=Aluno, y=max(data1$Total)+15, label=Aluno), color="black", fontface="bold",alpha=0.6, size=4, inherit.aes = FALSE, angle=90) 
p
```


### CE001-N

```{r notasn}
n <- read.csv("misc/notas_ce001-N.csv")
n <- n[order(n$Matrícula), ]
kable(n, row.names = FALSE)
```

```{r plotn, out.width = '100%'}
data1 <- rbind(n[which(rowSums(!is.na(n[,2:ncol(n)]))>0),], 
               data.frame(Matrícula='', n[1,-1]*0))
ns <- ncol(data1)-1
na <- nrow(data1)
data1$Total <- rowSums(data1[,2:(ns+1)], na.rm=TRUE)
data1$Aluno <- substring(data1$Mat, 8)
data1 <- data1[order(data1$Aluno),]
angle <- 90 -360*(1:na-0.5)/na
data1$angle <- ifelse(angle<(-90), angle + 180, angle)
data <- data.frame(
  Aluno=rep(data1$Aluno, ns), 
  Etapa=rep(paste0('E', 1:ns), each=na), 
  Nota=unlist(data1[,2:(ns+1)]))
p = ggplot(data) +      
  # Add the stacked bar
  geom_bar(aes(x=as.factor(Aluno), y=Nota, fill=Etapa), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete=TRUE) +
  ##geom_abline(slope=0, intercept=0:ns*70, col=c('gray'))+
  geom_abline(slope=0, intercept=c(ns*c(40,70), 7*70), col=c('red', 'green', 'blue'))+
##  annotate("text", x = rep(1.5, ns+1), y = 70*0:ns, label = sprintf('%02d', 70*0:ns) , color="brown", size=3, hjust=1, angle=45) +
  annotate("text", x = 1, y = c(ns*c(40,70), 7*70), label = sprintf('%02d', c(ns*c(40,70), 7*70)), color=c('red','green','blue'), size=4 , angle=45, hjust=0.5) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0,4), "cm") 
  ) +
  geom_text(data=data1, aes(x=Aluno, y=max(data1$Total)+50, label=Aluno), color="black", fontface="bold",alpha=0.6, size=3, angle=data1$angle, inherit.aes = FALSE ) +
  coord_polar()  
  ##geom_text(data=data1, aes(x=Aluno, y=max(data1$Total)+15, label=Aluno), color="black", fontface="bold",alpha=0.6, size=4, inherit.aes = FALSE, angle=90) 
```

### CE003-MN

```{r notasmn}
mn <- read.csv("misc/notas_ce003-MN.csv")
mn <- mn[order(mn$Matrícula), ]
kable(mn, row.names = FALSE)
```

```{r plotmn, out.width = '100%'}
data1 <- rbind(mn[which(rowSums(!is.na(mn[,2:ncol(mn)]))>0),], 
               data.frame(Matrícula='', mn[1,-1]*0))
ns <- ncol(data1)-1
na <- nrow(data1)
data1$Total <- rowSums(data1[,2:(ns+1)], na.rm=TRUE)
data1$Aluno <- substring(data1$Mat, 8)
data1 <- data1[order(data1$Aluno),]
angle <- 90 -360*(1:na-0.5)/na
data1$angle <- ifelse(angle<(-90), angle + 180, angle)
data <- data.frame(
  Aluno=rep(data1$Aluno, ns), 
  Etapa=rep(paste0('E', 1:ns), each=na), 
  Nota=unlist(data1[,2:(ns+1)]))
p = ggplot(data) +      
  # Add the stacked bar
  geom_bar(aes(x=as.factor(Aluno), y=Nota, fill=Etapa), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete=TRUE) +
  ##geom_abline(slope=0, intercept=0:ns*70, col=c('gray'))+
  geom_abline(slope=0, intercept=c(ns*c(40,70), 7*70), col=c('red', 'green', 'blue'))+
##  annotate("text", x = rep(1.5, ns+1), y = 70*0:ns, label = sprintf('%02d', 70*0:ns) , color="brown", size=3, hjust=1, angle=45) +
  annotate("text", x = 1, y = c(ns*c(40,70), 7*70), label = sprintf('%02d', c(ns*c(40,70), 7*70)), color=c('red','green','blue'), size=4 , angle=45, hjust=0.5) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0,4), "cm") 
  ) +
  geom_text(data=data1, aes(x=Aluno, y=max(data1$Total)+50, label=Aluno), color="black", fontface="bold",alpha=0.6, size=3, angle=data1$angle, inherit.aes = FALSE ) +
  coord_polar()  
  ##geom_text(data=data1, aes(x=Aluno, y=max(data1$Total)+15, label=Aluno), color="black", fontface="bold",alpha=0.6, size=4, inherit.aes = FALSE, angle=90) 
```
